server:
  port: 8082
  servlet:
    context-path: '/rentalmovie-movie/'

spring:
  application:
    name: rentalmovie-movie-service
  datasource:
    url: jdbc:postgresql://localhost:5432/movie
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

rm:
  serviceRegistry:
    username: serviceregistry
    password: 'rm123sr'
  auth:
    jwtSecret: FhCH5aXYk0VGbgxQCHY9lP1cNjhO7MZH

eureka:
  client:
    service-url:
      defaultZone: 'http://${rm.serviceRegistry.username}:${rm.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost