server:
  port: 8761

spring:
  application:
    name: rentalmovie-service-registry

rm:
  serviceRegistry:
    username: serviceregistry
    password: 'rm123sr'

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: 'http://${rm.serviceRegistry.username}:${rm.serviceRegistry.password}@localhost:8761/eureka'
      