server:
  port: 8000
spring:
  application:
    name: rentalmovie-api-gateway
  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri: lb://RENTALMOVIE-AUTHUSER-SERVICE
          predicates:
            - Path=/rentalmovie-authuser/**
        - id: movie-service
          uri: lb://RENTALMOVIE-MOVIE-SERVICE
          predicates:
            - Path=/rentalmovie-movie/**
        - id: order-service
          uri: lb://RENTALMOVIE-ORDER-SERVICE
          predicates:
            - Path=/rentalmovie-order/**

rm:
  serviceRegistry:
    username: serviceregistry
    password: 'rm123sr'

eureka:
  client:
    service-url:
      defaultZone: 'http://${rm.serviceRegistry.username}:${rm.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost

