server:
  port: 8000
spring:
  application:
    name: rentalmovie-api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: authuser-service
            uri: lb://RENTALMOVIE-AUTHUSER-SERVICE
            predicates:
              - Path=/rentalmovie-authuser/**
          - id: movie-service
            uri: lb://RENTALMOVIE-MOVIE-SERVICE
            predicates:
              - Path=/rentalmovie-movie/**
eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
