server:
  port: 8081
  servlet:
    context-path: '/rentalmovie-authuser/'

spring:
  application:
    name: rentalmovie-authuser-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authuser
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost