server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DevHenriqueRamos/rentalmovie-config-server-repo
          default-label: main
          username: devhenriqueramos
          password: ${GITHUB_TOKEN}

rm:
  configServer:
    username: configserver
    password: 'rm123cs'

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY_URI}
  instance:
    hostname: localhost